# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actui < Formula
  desc "actui is a TUI for managing act workflows"
  homepage "https://github.com/reecelikesramen/actui"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Darwin_x86_64.tar.gz"
      sha256 "70f365265576256ad0aa151f2118a61f4f3edeb1b00203eb7d3a05b0224ce41b"

      def install
        bin.install "actui"
      end
    end
    on_arm do
      url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Darwin_arm64.tar.gz"
      sha256 "8b789f58750e31d1c6fcaf43c11fdc60662d51b01075b570621299a3d44a3ee8"

      def install
        bin.install "actui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Linux_x86_64.tar.gz"
        sha256 "617fc831db24097adf2f59d9ff0ee0af0b995542a561b9f0c3bf41232135686f"

        def install
          bin.install "actui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Linux_arm64.tar.gz"
        sha256 "6c086a2474c3bb45ff2027327439dd2ba4b6f51564c7a81863ba09643022ad45"

        def install
          bin.install "actui"
        end
      end
    end
  end
end
