# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actui < Formula
  desc "actui is a TUI for managing act workflows"
  homepage "https://github.com/reecelikesramen/actui"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Darwin_x86_64.tar.gz"
      sha256 "26b924ee46c240176190d074ba51cd8a3ceb8745625c643c71271a15bf1d57dc"

      def install
        bin.install "actui"
      end
    end
    on_arm do
      url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Darwin_arm64.tar.gz"
      sha256 "25bf39092336011448fc4ded9b2b2ef6551b1913f01f5bf74db52abfcc533bb0"

      def install
        bin.install "actui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Linux_x86_64.tar.gz"
        sha256 "74c470fdd89458b045869aaaa054d4a959c97f3132d957b26f878bc79cc8cd0a"

        def install
          bin.install "actui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reecelikesramen/actui/releases/download/v0.1.0/actui_Linux_arm64.tar.gz"
        sha256 "c776b4a5c28af9e47fed1b45e1d5a8b49ce50cda5920a6220adfa8aab09293b9"

        def install
          bin.install "actui"
        end
      end
    end
  end
end
